linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc

linters:
  enable:
    - staticcheck
    - gosimple
    - revive
    - govet
    - unconvert
    - unused
    - gosec
    - gocyclo
    - dupl
    - misspell
    - unparam
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - prealloc
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: 'Deferring unsafe method "Close" on type "io.ReadCloser"'
      linters:
        - gosec
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false