name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        run: |
          go get -v
          go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go build -race
        env:
          GO111MODULE: "on"
          TZ: "America/Chicago"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.63

      - name: install goveralls
        run: |
          go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}